### PR TITLE
remove: dropzone.bitkubnext.app from blacklist

### PR DESCRIPTION
**Pull request by isman-usoh**
Hi,

Domain dropzone.bitkubnext.com is Official project from [Bitkub Blockchain Technology Co., Ltd](https://www.bitkubblockchain.com/) on [Bitkub Chain](https://www.bitkubchain.com/)

Project [announcement](https://www.facebook.com/105013668422174/posts/pfbid0QjtedpWkeMoUkXKbzjeufwyAhETqhk9iebKczEPTpgSrUncBFwY8uS7pH3eDm9Lul/)

It has been unfortunately blacklisted by mistake.

Thanks for your help.

### CODE REVIEW

**Comment by shrestha-milann** [comment]
Hi,

Thanks for the heads up.
We have removed the domain from the blacklist. It will take a few minutes
to reflect.
If the issue persists, please let us know.

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by isman-usoh** [comment]
Thank you @shrestha-milann

**Comment by isman-usoh** [comment]
Hi, @shrestha-milann 

What’s the status of this PR?

**Comment by shrestha-milann** [comment]
Hi Usoh,

The domain has already been removed from the blacklist.
You can confirm from the following:
https://lookup.phishfort.com/api/lookup?domain=dropzone.bitkubnext.app

Warm Regards,

Milan Shrestha

Anti-Phishing Operations

***@***.***

phishfort.com <https://www.phishfort.com/>

<https://www.linkedin.com/company/phishfort/>   <https://t.me/phishfort>
<https://twitter.com/PhishFort>

**Comment by isman-usoh** [comment]
@shrestha-milann Thank you.

**Pull request closed without merging**
