### PR TITLE
remove Yandex.Cloud Object Storage from blacklist and add service host in hostingproviders file

### PR DESCRIPTION
**Pull request by antonydevanchi**
From [Yandex Cloud Object Storage](https://cloud.yandex.com/en/docs/storage/concepts/bucket) documentation:

> Bucket URL
> You can use the following URL format to access a bucket:
> https://storage.yandexcloud.net/<bucket>?<parameters>
> http://<bucket>.storage.yandexcloud.net?<parameters>

### CODE REVIEW

**Comment by antonydevanchi** [comment]
@xtr3sor just unblock S3 storage of biggest IaaS-provider in Russia. 

Review changes ASAP, please.

**Comment by xtr3sor** [comment]
> @xtr3sor just unblock S3 storage of biggest IaaS-provider in Russia.
> 
> Review changes ASAP, please.

Hello Antony.

Can you share with me ALL domains from Yandex.ru and Yandex.com?

Thanks.

**Comment by antonydevanchi** [comment]
> > @xtr3sor just unblock S3 storage of biggest IaaS-provider in Russia.
> > Review changes ASAP, please.
> 
> Hello Anton.
> 
> Can you share with me ALL domains from Yandex.ru, Yandex.net and Yandex.com? (I'm needing all tlds)
> 
> Thanks.

I can't provide requested information because I not part Yandex. Also, I don't understand how it help us just remove host of infrastructure service uses many businesses across world?

**Comment by xtr3sor** [comment]
Thanks. The removal is on his way.

Best regards.

**Pull request closed without merging**
